In [4]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
file_1='youtube_dataset .csv'

In [6]:
#read CSV
raw_df = pd.read_csv(file_1)

In [10]:
raw_df

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,€66.9K - €1.1M,€802.3K - €12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,€635.6K - €10.2M,€7.6M - €122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,€0 - €0,€0 - €0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,€0 - €0,€0 - €0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,€0 - €0,€0 - €0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3939,1553037913-3921,https://socialblade.com/youtube/top/5000/mosts...,Genius,https://socialblade.com/youtube/c/genius?,genius,0,20,0,NaN,Games,"Aug 28th, 2005",D-,NaN,https://youtube.com/channel/UCdNvF54AYp2qRt8Dk...,NaN,NaN,NaN,https://youtube.com/channel/UCdNvF54AYp2qRt8Dk...,€0 - €0,€0 - €0
3940,1553024302-913,https://socialblade.com/youtube/top/5000/mosts...,Wolfychu,https://socialblade.com/youtube/c/wolfychu,WolfyChu,16,18,757,NaN,NaN,"Feb 10th, 2008",TBD,NaN,https://youtube.com/channel/UCylrI37DWJfPPo8W2...,NaN,NaN,NaN,https://youtube.com/channel/UCylrI37DWJfPPo8W2...,€0.65 - €10,€8 - €124
3941,1553034470-3276,https://socialblade.com/youtube/top/5000/mosts...,FRANKIEonPC,https://socialblade.com/youtube/c/frankieonpc,frankieonpc,0,16,0,GB,Games,--,B-,NaN,https://youtube.com/channel/UCHF3A1sMkv7Q0ywaz...,NaN,NaN,NaN,https://youtube.com/channel/UCHF3A1sMkv7Q0ywaz...,€195 - €3.1K,€2.3K - €37.5K
3942,1553040011-4402,https://socialblade.com/youtube/top/5000/mosts...,Hi Gorgeous Anna Layza,https://socialblade.com/youtube/c/higorgeous,higorgeous,1,16,918,NaN,Comedy,"Jan 2nd, 2007",B+,NaN,https://youtube.com/channel/UClrGcMQweED1oqTES...,NaN,NaN,NaN,https://youtube.com/channel/UClrGcMQweED1oqTES...,€19.9K - €318.2K,€238.7K - €3.8M
3943,1553027486-1650,https://socialblade.com/youtube/top/5000/mosts...,Druzhko Show,https://socialblade.com/youtube/c/druzhkoshow,druzhko show,0,12,0,NaN,NaN,"Jan 30th, 2017",D-,NaN,https://youtube.com/channel/UCFYVnwfusuBfdNlKQ...,NaN,NaN,NaN,https://youtube.com/channel/UCFYVnwfusuBfdNlKQ...,€0 - €0,€0 - €0

In [8]:
#sort dataframe based on views
df1=raw_df.sort_values(by='subscribers', axis=0, ascending=False)
df1

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,€66.9K - €1.1M,€802.3K - €12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,€635.6K - €10.2M,€7.6M - €122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,€0 - €0,€0 - €0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,€0 - €0,€0 - €0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,€0 - €0,€0 - €0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3939,1553037913-3921,https://socialblade.com/youtube/top/5000/mosts...,Genius,https://socialblade.com/youtube/c/genius?,genius,0,20,0,NaN,Games,"Aug 28th, 2005",D-,NaN,https://youtube.com/channel/UCdNvF54AYp2qRt8Dk...,NaN,NaN,NaN,https://youtube.com/channel/UCdNvF54AYp2qRt8Dk...,€0 - €0,€0 - €0
3940,1553024302-913,https://socialblade.com/youtube/top/5000/mosts...,Wolfychu,https://socialblade.com/youtube/c/wolfychu,WolfyChu,16,18,757,NaN,NaN,"Feb 10th, 2008",TBD,NaN,https://youtube.com/channel/UCylrI37DWJfPPo8W2...,NaN,NaN,NaN,https://youtube.com/channel/UCylrI37DWJfPPo8W2...,€0.65 - €10,€8 - €124
3941,1553034470-3276,https://socialblade.com/youtube/top/5000/mosts...,FRANKIEonPC,https://socialblade.com/youtube/c/frankieonpc,frankieonpc,0,16,0,GB,Games,--,B-,NaN,https://youtube.com/channel/UCHF3A1sMkv7Q0ywaz...,NaN,NaN,NaN,https://youtube.com/channel/UCHF3A1sMkv7Q0ywaz...,€195 - €3.1K,€2.3K - €37.5K
3942,1553040011-4402,https://socialblade.com/youtube/top/5000/mosts...,Hi Gorgeous Anna Layza,https://socialblade.com/youtube/c/higorgeous,higorgeous,1,16,918,NaN,Comedy,"Jan 2nd, 2007",B+,NaN,https://youtube.com/channel/UClrGcMQweED1oqTES...,NaN,NaN,NaN,https://youtube.com/channel/UClrGcMQweED1oqTES...,€19.9K - €318.2K,€238.7K - €3.8M
3943,1553027486-1650,https://socialblade.com/youtube/top/5000/mosts...,Druzhko Show,https://socialblade.com/youtube/c/druzhkoshow,druzhko show,0,12,0,NaN,NaN,"Jan 30th, 2017",D-,NaN,https://youtube.com/channel/UCFYVnwfusuBfdNlKQ...,NaN,NaN,NaN,https://youtube.com/channel/UCFYVnwfusuBfdNlKQ...,€0 - €0,€0 - €0

In [19]:
#subset the dataframe 
df2=df1.iloc[0:1000, :]
df2

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,€66.9K - €1.1M,€802.3K - €12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,€635.6K - €10.2M,€7.6M - €122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,€0 - €0,€0 - €0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,€0 - €0,€0 - €0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,€0 - €0,€0 - €0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1553037784-3900,https://socialblade.com/youtube/top/5000/mosts...,GloZell Green,https://socialblade.com/youtube/user/glozell1,GloZell Green,2316,4719893,845298432,US,Comedy,"Jan 26th, 2008",B-,NaN,https://youtube.com/channel/UC7FhOuPmxz8spz_xv...,NaN,https://instagram.com/glozell/,NaN,https://plus.google.com/110057581739311657068,€228 - €3.7K,€2.7K - €43.8K
996,1553037792-3901,https://socialblade.com/youtube/top/5000/mosts...,ETV Jabardasth,https://socialblade.com/youtube/c/etvjabardasth,ETV Jabardasth,3735,4719652,4290216700,IN,People,"Jul 14th, 2015",A,NaN,https://youtube.com/channel/UCnoqvTW4YZExfDeq7...,NaN,NaN,NaN,https://youtube.com/channel/UCnoqvTW4YZExfDeq7...,€50.5K - €808K,€606K - €9.7M
997,1553037768-3897,https://socialblade.com/youtube/top/5000/mosts...,The Timeliners,https://socialblade.com/youtube/c/thetimeliners,The Timeliners,191,4718880,459254149,IN,Entertainment,"Feb 1st, 2014",B+,NaN,https://youtube.com/channel/UCTlnaHHQ75zlDg_fL...,NaN,https://www.instagram.com/thetimeliners/,NaN,https://plus.google.com/102509388716102017341,€5.6K - €90.3K,€67.7K - €1.1M
998,1553037724-3888,https://socialblade.com/youtube/top/5000/mosts...,Crafty Panda,https://socialblade.com/youtube/channel/UC03Rv...,Crafty Panda,84,4712345,890158507,US,Howto,"Dec 3rd, 2017",A,NaN,https://youtube.com/channel/UC03RvJoIhm_fMwlUp...,NaN,NaN,NaN,https://youtube.com/channel/UC03RvJoIhm_fMwlUp...,€38.6K - €617.4K,€463.1K - €7.4M
999,1553037758-3896,https://socialblade.com/youtube/top/5000/mosts...,Troom Troom PT,https://socialblade.com/youtube/channel/UCgCQl...,Troom Troom PT,444,4711742,880150449,NaN,NaN,"Apr 19th, 2015",A-,NaN,https://youtube.com/channel/UCgCQlMYN2XypwYC2w...,NaN,https://www.facebook.com/troomhands,NaN,https://www.instagram.com/troomtroom/,€16.4K - €261.8K,€196.3K - €3.1M

In [71]:
#Grouping and perform count over each group
subs_group =  df2.groupby('userID').count()

In [56]:
subs_group

                  uploads  subscribers  videoviews
userID
#Education              0     10334917           0
#Mind Warehouse       350      5672610  1642709337
#Refugio Mental       307      8406958  1711273254
#Refúgio Mental       323      8580557  1309149535
1Kilo Oficial         126      5596715  1062790300
...                   ...          ...         ...
whinderssonnunes      362     35123697  2858803818
wifistudy            9873      7029576   669955562
zayn                   11      9371581    43661783
zbing z.             1524      8494739  3236417476
Área Secreta          784      7991215   981134353

[999 rows x 3 columns]

In [68]:
#sort dataframe based on views
df2=subs_group.sort_values(by='subscribers', axis=0, ascending=False)
df2

                uploads  subscribers   videoviews
userID
PewDiePie          3779     90210848  20772365682
T-Series          13218     90194329  65092058996
Gaming                0     81888222            0
YouTube Movies        0     77413743            0
Sports                0     75622870            0
...                 ...          ...          ...
GloZell Green      2316      4719893    845298432
ETV Jabardasth     3735      4719652   4290216700
The Timeliners      191      4718880    459254149
Crafty Panda         84      4712345    890158507
Troom Troom PT      444      4711742    880150449

[999 rows x 3 columns]

In [58]:
import csv

In [60]:
df2.to_csv (r'C:\Users\Pavan\Desktop\Assignments\1202 assignments\Assignment 4\sorted_YT.csv', index = False, header=True)

In [77]:
dd=df1['channeltype'].value_counts()

In [78]:
dd

Entertainment    1037
Music             760
Games             449
People            392
Comedy            275
Howto             223
Film              176
Education         142
Tech               78
Sports             56
News               55
Autos              14
Travel             11
Animals             9
Nonprofit           3
Shows               1
Name: channeltype, dtype: int64

In [ ]:
df1[ctcv]=df1.apply(np.value_count, axis=1)

In [21]:
df2['channeltype'].value_counts()

Entertainment    284
Music            240
Games            115
Comedy            76
People            72
Howto             49
Film              36
Education         30
Tech              19
Sports            17
News              17
Autos              3
Animals            2
Nonprofit          1
Travel             1
Name: channeltype, dtype: int64

In [22]:
#rawdata
raw_df
#sort dataframe based on subscribers
df1=raw_df.sort_values(by='subscribers', axis=0, ascending=False)
df1
#subset the dataframe for top 1000 
df2=df1.iloc[0:1000, :]
df2
#channeltype
df2['channeltype'].value_counts()

Entertainment    284
Music            240
Games            115
Comedy            76
People            72
Howto             49
Film              36
Education         30
Tech              19
Sports            17
News              17
Autos              3
Animals            2
Nonprofit          1
Travel             1
Name: channeltype, dtype: int64